#!/usr/bin/env nextflow
// Copyright (C) 2024 Genome Research Ltd.

/*
========================================================================================
    HELP
========================================================================================
*/

def logo = NextflowTool.logo(workflow, params.monochrome_logs)

log.info logo

NextflowTool.commandLineParams(workflow.commandLine, log, params.monochrome_logs)


def printHelp() {
    NextflowTool.help_message("${workflow.ProjectDir}/schema.json", 
                               [],
    params.monochrome_logs, log)
}

/*
========================================================================================
    IMPORT MODULES/SUBWORKFLOWS
========================================================================================
*/
include { MIXED_INPUT           } from './assorted-sub-workflows/mixed_input/mixed_input.nf'
include { SYLPH_REFSET          } from './assorted-sub-workflows/sylph_refset/sylph_refset.nf'
include { PREP_REFS;             
          POPPUNK;                
          ORDER_GROUPS          } from './modules/poppunk.nf'
include { PUBLISH_GROUPS;
          PUBLISH_REPS          } from './modules/publish_intermediates.nf'
include { THEMISTO_BUILD_INDEX; 
          THEMISTO_PSEUDOALIGN;
          THEMISTO_STATS        } from './modules/themisto.nf'
include { MSWEEP                } from './modules/msweep.nf'
include { MGEMS                 } from './modules/mgems.nf'

//
// SUBWORKFLOWS
//
include { DEREP_GROUPS } from './subworkflows/derep_groups.nf'

include { VALIDATE_PREBUILT_INPUT } from './subworkflows/validate_prebuilt_input.nf'

/*
Helper Scripts
*/

include { validate_params;
          validate_references } from './modules/validate.nf'

/*
========================================================================================
    RUN MAIN WORKFLOW
========================================================================================
*/

workflow {
    // params.each { key, value ->
    // log.info "PARAM ${key} = ${value}" // for dev/ debugging
    // }

    if (params.help) {
        printHelp()
        exit 0
    }

    validate_params()

    reads_ch = MIXED_INPUT()    // outputs channel of [meta, R1, R2] for reads_<1|2>.fastq.gz

    if (params.references || params.sylph_refset) {
        if (params.references) {
            // Check references exist and are not duplicated or fail early
            validate_references(params.references)

            // Set up input channels starting from references.txt
            references_ch = channel.fromPath(params.references).first()
        } else {
            // Generate candidate references from reads via Sylph.
            SYLPH_REFSET(reads_ch)
            references_ch = SYLPH_REFSET.out.references
        }

        PREP_REFS(references_ch)
        POPPUNK(PREP_REFS.out.refs_csv)
        poppunk_clusters_csv = POPPUNK.out.clusters

        if (params.refine_refs) {
            poppunk_dists_ch = POPPUNK.out.dist_matrix
            DEREP_GROUPS(poppunk_clusters_csv, poppunk_dists_ch)

            references_ch
            | splitCsv
            | map { ref_path_list ->
                ref_path_list[0]
                // get ref_label as generated by poppunk and map to path
                def ref_label = file(ref_path_list[0]).baseName.replace(".", "_")
                [ref_path_list[0], ref_label]
            }
            | set { ref_label_paths }

            DEREP_GROUPS.out.chosen_representatives
            | join(ref_label_paths, by: 1)
            | map { ref_label, meta, rep_path ->
                [meta.cluster, rep_path]
            }
            | set { clusters_rep_paths }

            // split out clusters and paths into seperate files for positionally consistent files in index and core workflow
            clusters_rep_paths
            | collectFile { cluster, rep_path -> ["representatives.txt", "${rep_path}\n"] }
            | first()
            | set { representatives_ch }

            PUBLISH_REPS(representatives_ch)
            
            clusters_rep_paths
            | collectFile { cluster, rep_path -> ["groups.txt", "${cluster}\n"] }
            | first()
            | set {ref_groups_ch} // groups file for representatives only

            PUBLISH_GROUPS(ref_groups_ch)

        } else {
        
            ref_groups_ch = ORDER_GROUPS(PREP_REFS.out.refs_csv, poppunk_clusters_csv).groups
            representatives_ch = references_ch // no dereplication

        }

        index_prefix_ch = channel.value("index") // needs to be identical to what index is set as in indexing process
        index_files_ch = THEMISTO_BUILD_INDEX(index_prefix_ch, representatives_ch).collect()
        
        // Output stats on the index (not required for anything just an additional output)
        THEMISTO_STATS(index_files_ch, index_prefix_ch)

    } else {
        // Set up input channels starting from pre-built index AND provided ref_groups
        ref_groups_ch = channel.fromPath(params.ref_groups).first()
        index_files_ch = channel.fromPath("${params.themisto_index}*{tdbg,tcolors}").collect()
        index_prefix_ch = channel.value(file(params.themisto_index).getName())

        // Validate
        VALIDATE_PREBUILT_INPUT(index_files_ch, index_prefix_ch)
    }

    // Core Workflow
    pseudoaligned_ch = THEMISTO_PSEUDOALIGN(reads_ch, index_files_ch, index_prefix_ch)
    
    msweep_ch = MSWEEP(pseudoaligned_ch, ref_groups_ch)
    
    MGEMS(
        reads_ch
            .join(pseudoaligned_ch, by: 0)
            .join(msweep_ch, by: 0)
            .map { meta, r1, r2, aln1, aln2, abund, probs ->
                tuple(meta, r1, r2, aln1, aln2, abund, probs)
            },
            index_files_ch,
            index_prefix_ch,
            ref_groups_ch
    )
}
