include { SPLIT_CLUSTERS_CSV;
          SPLIT_DIST_MATRIX;
          GENERATE_TOTAL_DIST_MATRIX;
          SUBSELECT_GRAPH;            } from '../modules/refine_refs.nf'
include { PUBLISH_GROUPS;
          PUBLISH_REPS                } from '../modules/publish_intermediates.nf'

workflow REFINE_REFS {
    take:
    clustered_refs  // tuple(meta, references, clusters_csv, sparse_dist_matrix)

    main:
    clustered_refs
    | multiMap { meta, references, clusters_csv, sparse_dist_matrix ->
        references: [meta, references]
        clusters_with_dist_matrix: [meta, clusters_csv, sparse_dist_matrix]
    }
    | set { refs_info }

    DEREP_GROUPS(clustered_refs)

    refs_info.references
    | splitCsv
    | map { meta, ref_path_list ->
        // get ref_label as generated by poppunk and map to path
        def ref_label = file(ref_path_list[0]).baseName.replace(".", "_")
        [meta, ref_path_list[0], ref_label]
    }
    | set { ref_label_paths }

    // TODO DELETE DEBUG CODE...
    // ref_label_paths
    // | randomSample(10)
    // | view()

    // DEREP_GROUPS.out.chosen_representatives
    // | randomSample(10)
    // | view()

    // DEREP_GROUPS.out.chosen_representatives
    // | splitCsv
    // | randomSample(10)
    // | view()

    // TODO Uncomment the below to test the next part of the pipeline
    // DEREP_GROUPS.out.chosen_representatives
    // | join(ref_label_paths, by: 2)
    // | map { ref_label, meta, rep_path ->
    //     [meta.cluster, rep_path]
    // }
    // | set { clusters_rep_paths }

    // clusters_rep_paths.view()


    // // Split out clusters and paths into separate files for positionally consistent files in index and core workflow
    // clusters_rep_paths
    // | collectFile { cluster, rep_path -> ["representatives.txt", "${rep_path}\n"] }
    // | first()
    // | set { representatives_ch }

    // PUBLISH_REPS(representatives_ch)

    // clusters_rep_paths
    // | collectFile { cluster, rep_path -> ["groups.txt", "${cluster}\n"] }
    // | first()
    // | set {ref_groups_ch} // groups file for representatives only

    // PUBLISH_GROUPS(ref_groups_ch)

    // emit:
    // representatives_ch
    // ref_groups_ch
}

workflow DEREP_GROUPS {
    take:
    clustered_refs  // tuple(meta, references, clusters_csv, pp_dist_matrix)

    main:
    // Idea - split clusters_csv into multiple smaller CSVs (one per cluster)
    // Then split the distance matrix per cluster - this would allow SPLIT_DIST_MATRIX to output just one CSV instead of multiple and should simplify whole workflow...

    clustered_refs
    | multiMap { meta, references, clusters_csv, pp_dist_matrix ->
        references: [meta, references]
        clusters_csv: [meta, clusters_csv]
        pp_dist_matrix: [meta, pp_dist_matrix]
    }
    | set { clusters_info }

    SPLIT_CLUSTERS_CSV(clusters_info.clusters_csv)

    SPLIT_CLUSTERS_CSV.out.split_cluster_csv
    | transpose // Emit one cluster CSV file at a time
    | branch { meta, cluster_csv ->
        no_derep: cluster_csv.readLines().size() <= params.representatives
        derep: cluster_csv.readLines().size() > params.representatives
    }
    | set { clusters }

    clusters_info.pp_dist_matrix
    | join(clusters.derep)
    | join(clusters_info.references)
    | SPLIT_DIST_MATRIX

    SPLIT_DIST_MATRIX.out.cluster_dists
    | transpose
    | map { meta, path ->
        def new_meta = [:]
        new_meta.ID = meta.ID
        new_meta.cluster = path.name.split("_")[0]
        [new_meta, path]
    }
    | GENERATE_TOTAL_DIST_MATRIX
    | SUBSELECT_GRAPH

    // Ensure we represent the genomes that are not to be dereplicated
    // TODO: Potentially group representatives per species and join to the clusters that have not been dereplicated, instead of mixing as we are currently doing.
    SUBSELECT_GRAPH.out.representatives
    | mix(clusters.no_derep)
    | collectFile
    | set { chosen_representatives }

    emit:
    chosen_representatives
}