include { SPLIT_CLUSTERS_CSV;
          SPLIT_DIST_MATRIX;
          GENERATE_TOTAL_DIST_MATRIX;
          SUBSELECT_GRAPH;
          NORMALISE_REFERENCE_LIST;
          EXTRACT_REF_LABEL;
          BUILD_REFERENCE_CLUSTER_FILES; } from '../modules/refine_refs.nf'
include { PUBLISH_GROUPS;
          PUBLISH_REPS                } from '../modules/publish_intermediates.nf'

workflow REFINE_REFS {
    take:
    clustered_refs  // tuple(meta, references, clusters_csv, sparse_dist_matrix)

    main:
    clustered_refs
    | multiMap { meta, references, clusters_csv, sparse_dist_matrix ->
        references: [meta, references]
        clusters_with_dist_matrix: [meta, clusters_csv, sparse_dist_matrix]
    }
    | set { refs_info }

    DEREP_GROUPS(clustered_refs)

    // TODO - Switch to pandas implementation 
    EXTRACT_REF_LABEL(refs_info.references)

    // refs_info.references
    // | splitCsv
    // | map { meta, ref_path_list ->
    //     // get ref_label as generated by poppunk and map to path
    //     def ref_label = file(ref_path_list[0]).baseName.replace(".", "_")
    //     [meta, ref_label, ref_path_list[0]]
    // }
    // | collectFile { ref_label_tuple ->
    //     ["${ref_label_tuple[0].ID}_ref_paths.csv", "${ref_label_tuple[1]},${ref_label_tuple[2]}\n"]
    // }
    // | set { ref_label_paths }

    // ref_label_paths.view()

    refs_info.clusters_with_dist_matrix
    | map { meta, clusters_csv, sparse_dist_matrix ->
        [meta, clusters_csv]
    }
    | set { clusters_csv }

    DEREP_GROUPS.out.chosen_representatives
    | map { chosen_representatives -> 
        def taxon = chosen_representatives.baseName.replace("_representatives", "")
        def meta = ["ID":taxon]
        [meta, chosen_representatives]
    }
    | set { chosen_representatives }

    chosen_representatives 
    | join(EXTRACT_REF_LABEL.out.ref_label_paths)
    | join(clusters_csv)
    | BUILD_REFERENCE_CLUSTER_FILES

    // TODO DELETE DEBUG CODE...
    // ref_label_paths
    // | randomSample(10)
    // | view()

    // DEREP_GROUPS.out.chosen_representatives
    // | randomSample(10)
    // | view()

    // DEREP_GROUPS.out.chosen_representatives
    // | splitCsv
    // | map -> { ref_label, cluster ->
    //     ref_label
    // }
    // | randomSample(10)
    // | view()

    // TODO Uncomment the below to test the next part of the pipeline
    // DEREP_GROUPS.out.chosen_representatives
    // | splitCsv
    // | map { tuple_output ->
    //     tuple_output[0]
    // }
    // | randomSample(10)
    // | view()

    // DEREP_GROUPS.out.chosen_representatives
    // | splitCsv
    // | map { tuple_output ->
    //     tuple_output[0]
    // }
    // | join(ref_label_paths)
    // | map { ref_label, meta, rep_path ->
    //     [meta, rep_path]
    // }
    // | set { clusters_rep_paths }

    // clusters_rep_paths.view()


    // // Split out clusters and paths into separate files for positionally consistent files in index and core workflow
    // clusters_rep_paths
    // | collectFile { cluster, rep_path -> ["representatives.txt", "${rep_path}\n"] }
    // | first()
    // | set { representatives_ch }

    // PUBLISH_REPS(representatives_ch)

    // clusters_rep_paths
    // | collectFile { cluster, rep_path -> ["groups.txt", "${cluster}\n"] }
    // | first()
    // | set {ref_groups_ch} // groups file for representatives only

    // PUBLISH_GROUPS(ref_groups_ch)

    // emit:
    // representatives_ch
    // ref_groups_ch
}

workflow DEREP_GROUPS {
    take:
    clustered_refs  // tuple(meta, references, clusters_csv, pp_dist_matrix)

    main:
    // Idea - split clusters_csv into multiple smaller CSVs (one per cluster)
    // Then split the distance matrix per cluster - this would allow SPLIT_DIST_MATRIX to output just one CSV instead of multiple and should simplify whole workflow...

    clustered_refs
    | multiMap { meta, references, clusters_csv, pp_dist_matrix ->
        references: [meta, references]
        clusters_csv: [meta, clusters_csv]
        pp_dist_matrix: [meta, pp_dist_matrix]
    }
    | set { clusters_info }

    SPLIT_CLUSTERS_CSV(clusters_info.clusters_csv)

    SPLIT_CLUSTERS_CSV.out.split_cluster_csv
    | transpose // Emit one cluster CSV file at a time
    | branch { meta, cluster_csv ->
        no_derep: cluster_csv.readLines().size() <= params.representatives
        derep: cluster_csv.readLines().size() > params.representatives
    }
    | set { clusters }

    clusters_info.pp_dist_matrix
    | join(clusters.derep)
    | join(clusters_info.references)
    | SPLIT_DIST_MATRIX

    SPLIT_DIST_MATRIX.out.cluster_dists
    | transpose
    | map { meta, path ->
        def new_meta = [:]
        new_meta.ID = meta.ID
        new_meta.cluster = path.name.split("_")[0]
        [new_meta, path]
    }
    | GENERATE_TOTAL_DIST_MATRIX
    | SUBSELECT_GRAPH

    // Ensure we represent the genomes that are not to be dereplicated
    clusters.no_derep
    | map { meta, reps_file ->
        def new_meta = meta + ["cluster": reps_file.baseName]
        [new_meta, reps_file]
    }
    | set {clusters_no_derep}

    SUBSELECT_GRAPH.out.representatives
    | mix(clusters_no_derep)
    | map { meta, rep_file ->
        [meta, rep_file]
    }
    | NORMALISE_REFERENCE_LIST  // Chosen representatives is a list of [meta, rep_file] where rep_file is heterogeneous because it contains "rep,cluster" for clusters_no_derep and "rep" alone for SUBSELECT_GRAPH.out.representatives. So quick helper to normalize.
    | collectFile { representatives_tuple -> 
        ["${representatives_tuple[0].ID}_representatives.txt", representatives_tuple[1].readLines().join("\n") + "\n"]  // Add last newline to ensure last line has a newline character too!
    }
    | set { chosen_representatives }

    chosen_representatives.view()

    // SUBSELECT_GRAPH.out.representatives
    // | map { meta, reps_file ->
    //     [meta.ID, meta, reps_file]
    // }
    // | mix(clusters_no_derep)
    // | map { taxon, meta, reps_file ->
    //     [taxon, meta.cluster, reps_file.readLines()]
    // }
    // | transpose
    // | groupTuple


    // | map { taxon, meta, reps ->
    //     def new_meta = [ID:taxon]
    //     [new_meta, meta.cluster, reps.readLines()]
    // }
    // | transpose
    // | set { rep_clusters }

    // rep_clusters
    // | collectFile { meta, cluster, rep ->
    //     ["${taxon}_reps.tsv", rep + "\n"]
    // }
    // | set { taxon_reps }
    
    // rep_clusters
    // | collectFile { meta, cluster, rep ->
    //     ["${taxon}_groups.tsv", cluster + "\n"]
    // }
    // | set { taxon_groups }



    // taxon_reps.view()
    // taxon_groups.view()

    // SUBSELECT_GRAPH.out.representatives
    // | mix(clusters.no_derep)
    // | collectFile
    // | set { chosen_representatives }

    emit:
    chosen_representatives
    // taxon_representatives
}