include { SPLIT_DIST_MATRIX           } from '../modules/refine_refs.nf'
include { GENERATE_TOTAL_DIST_MATRIX  } from '../modules/refine_refs.nf'
include { SUBSELECT_GRAPH             } from '../modules/refine_refs.nf'
include { PUBLISH_GROUPS;
          PUBLISH_REPS                } from '../modules/publish_intermediates.nf'

workflow REFINE_REFS {
    take:
    clustered_refs  // tuple(meta, references, clusters_csv, sparse_dist_matrix)

    main:
    clustered_refs
    | multiMap { meta, references, clusters_csv, sparse_dist_matrix ->
        references: [meta, references]
        clusters_with_dist_matrix: [meta, clusters_csv, sparse_dist_matrix]
    }
    | set { refs_info }

    DEREP_GROUPS(refs_info.clusters_with_dist_matrix)

    refs_info.references
    | splitCsv
    | map { meta, ref_path_list ->
        // get ref_label as generated by poppunk and map to path
        def ref_label = file(ref_path_list[0]).baseName.replace(".", "_")
        [meta, ref_path_list[0], ref_label]
    }
    | set { ref_label_paths }

    // DEREP_GROUPS.out.chosen_representatives
    // | join(ref_label_paths, by: 1)
    // | map { ref_label, meta, rep_path ->
    //     [meta.cluster, rep_path]
    // }
    // | set { clusters_rep_paths }


    // // Split out clusters and paths into separate files for positionally consistent files in index and core workflow
    // clusters_rep_paths
    // | collectFile { cluster, rep_path -> ["representatives.txt", "${rep_path}\n"] }
    // | first()
    // | set { representatives_ch }

    // PUBLISH_REPS(representatives_ch)
    
    // clusters_rep_paths
    // | collectFile { cluster, rep_path -> ["groups.txt", "${cluster}\n"] }
    // | first()
    // | set {ref_groups_ch} // groups file for representatives only

    // PUBLISH_GROUPS(ref_groups_ch)

    // emit:
    // representatives_ch
    // ref_groups_ch
}

workflow DEREP_GROUPS {
    take:
    clusters_with_dist_matrix  // tuple(meta, clusters_csv, pp_dist_matrix)

    main:
    clusters_with_dist_matrix
    | multiMap { meta, clusters_csv, pp_dist_matrix ->
        clusters_csv: [meta, clusters_csv]
        pp_dist_matrix: [meta, pp_dist_matrix]
    }
    | set { clusters_info }

    clusters_info.clusters_csv
    | splitCsv(header: true)
    | map { meta, row -> [meta, row.Taxon, row.Cluster] }  // Taxon = reference label
    | groupTuple(by:2)
    | map { metas, ref_labels, cluster -> [metas[0], ref_labels, cluster] }  // Get only first meta in list (remove duplicate metas)
    | branch {
        no_derep: it[1].size() < params.representatives
        derep: it[1].size() > params.representatives
    }
    | set { clusters }

    clusters.derep
    | transpose
    | collectFile { meta, sample, cluster ->
        [ "${meta.ID}_derep_samples.csv", [sample, cluster].join(",") + "\n" ]
    }
    | map { derep_samples_file ->
        def new_meta = ["ID": derep_samples_file.baseName.replace("_derep_samples", "")]
        [ new_meta, derep_samples_file ]
    }
    | set { clusters_multiple_samples }

    clusters_info.pp_dist_matrix
    | join(clusters_multiple_samples)
    | SPLIT_DIST_MATRIX

    SPLIT_DIST_MATRIX.out.cluster_dists
    | flatMap
    | map { meta, path ->
        def new_meta = [:]
        new_meta.ID = meta.ID
        new_meta.cluster = path.name.split("_")[0]
        [new_meta, path]
    }
    | GENERATE_TOTAL_DIST_MATRIX
    | SUBSELECT_GRAPH
    
    clusters.no_derep
    | transpose
    | map { meta, rep, cluster -> 
        def new_meta = meta.copy()
        new_meta.cluster = cluster
        [new_meta, rep]
    }
    | set { no_derep_representatives }

    SUBSELECT_GRAPH.out.representatives
    | splitCsv()
    | view()
    // | map { meta, reps -> 
    //     [[meta, reps[0]]]
    // }
    // | collect
    // | flatMap
    // | mix(no_derep_representatives)
    // | ifEmpty { error("Error: No representatives found") }
    // | set { chosen_representatives }

    // emit:
    // chosen_representatives
}